version : '2.2'
services : 
  nginx : 
    image : nginx:latest
    ports :
      - "80:80"
    volumes : 
      - ../build/:/usr/share/nginx/html/
      - ./conf/:/etc/nginx/conf.d/
  backend : 
    image : rebaseitlabs/cuttime:latest